# Generated by Django 4.2.4 on 2023-08-07 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medsenger_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsenger_agent.contract')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('voximplant_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('contracts', models.ManyToManyField(to='medsenger_agent.contract')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
