services:
  server:
    container_name: agents-voximplant-server
    build:
      context: .
      target: prod
      network: host
    restart: unless-stopped
    env_file: ".env"
    network_mode: "host"
    volumes:
      - ./:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      DJANGO_SETTINGS_MODULE: "voximplant_medsenger_bot.settings.production"
  worker:
    container_name: agents-voximplant-worker
    restart: unless-stopped
    env_file: ".env"
    network_mode: "host"
    build:
      context: .
      target: worker
      network: host
    environment:
      DJANGO_SETTINGS_MODULE: "voximplant_medsenger_bot.settings.production"
    depends_on:
      - server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

