services:
  server:
    container_name: agents-voximplant-server
    env_file: ".env"
    build:
      context: .
      target: dev
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    environment:
      DJANGO_SETTINGS_MODULE: "voximplant_medsenger_bot.settings.development"
  worker:
    container_name: agents-voximplant-worker
    env_file: ".env"
    build:
      context: .
      target: worker
    environment:
      DJANGO_SETTINGS_MODULE: "voximplant_medsenger_bot.settings.development"
    depends_on:
      - server
