# Generated by Django 4.2.4 on 2023-08-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agent_token', models.CharField(max_length=255)),
            ],
        ),
    ]
